name: 'Setup Wiremock'
author: 'William Haw'
branding:
  icon: 'box'
  color: 'orange'
description: 'Setup a standalone Wiremock process with stubs defined in JSON files'
inputs:
  mappings:
    description: 'Path to folder with JSON stubs (as described in http://wiremock.org/docs/running-standalone/#json-file-configuration)'
    required: true
    default: 'wiremock-mappings'
  files:
    description: 'Path to folder with static files (as described in http://wiremock.org/docs/running-standalone/#json-file-configuration)'
    required: true
    default: 'wiremock-files'
  command:
    description: 'Command to run API tests'
    required: true
    default: 'node --version'
  http-port:
    description: 'Port on which to run Wiremock'
    required: false
    default: '8080'
  verbose:
    description: 'Turn on WireMock verbose logging'
    required: false
    default: false
outputs:
  wiremock-stdout:
    description: 'Logs from Wiremock'
runs:
  using: 'node16'
  main: 'index.js'